version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD:-YourStrong@Passw0rd}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - cancapp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD:-YourStrong@Passw0rd} -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching and Hangfire
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cancapp-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Main API Application
  api:
    build:
      context: .
      dockerfile: CanaApp.Apis/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CancApp;User Id=sa;Password=${DB_PASSWORD:-YourStrong@Passw0rd};Encrypt=False;TrustServerCertificate=True
      - ConnectionStrings__HangfireConnection=Server=sqlserver;Database=CANCAppJobs;User Id=sa;Password=${DB_PASSWORD:-YourStrong@Passw0rd};Encrypt=False;TrustServerCertificate=True
      - Jwt__Key=${JWT_KEY:-YourSuperSecretJwtKeyHereMakeItLongAndSecure}
      - MailSettings__Password=${MAIL_PASSWORD}
      - HangfireSettings__UserName=${HANGFIRE_USER:-admin}
      - HangfireSettings__Password=${HANGFIRE_PASSWORD:-admin123}
      - Redis__ConnectionString=redis:6379,password=${REDIS_PASSWORD:-redis123}
    depends_on:
      - sqlserver
      - redis
    networks:
      - cancapp-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  sqlserver_data:
    driver: local
  redis_data:
    driver: local

networks:
  cancapp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 