version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD:-YourStrong@Passw0rd}
      - MSSQL_PID=Express
      - MSSQL_MEMORY_LIMIT_MB=4096
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - cancapp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD:-YourStrong@Passw0rd} -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  # Main API Application
  api:
    build:
      context: .
      dockerfile: CanaApp.Apis/Dockerfile
      target: final
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CancApp;User Id=sa;Password=${DB_PASSWORD:-YourStrong@Passw0rd};Encrypt=False;TrustServerCertificate=True;MultipleActiveResultSets=True;Connection Timeout=30;Command Timeout=30
      - ConnectionStrings__HangfireConnection=Server=sqlserver;Database=CANCAppJobs;User Id=sa;Password=${DB_PASSWORD:-YourStrong@Passw0rd};Encrypt=False;TrustServerCertificate=True;MultipleActiveResultSets=True;Connection Timeout=30;Command Timeout=30
      - Jwt__Key=${JWT_KEY:-YourSuperSecretJwtKeyHereMakeItLongAndSecure}
      - MailSettings__Password=${MAIL_PASSWORD}
      - HangfireSettings__UserName=${HANGFIRE_USER:-admin}
      - HangfireSettings__Password=${HANGFIRE_PASSWORD:-admin123}
      - DOTNET_RUNNING_IN_CONTAINER=true
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - cancapp-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  sqlserver_data:
    driver: local

networks:
  cancapp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 